### ISSUE TITLE
RESTFUL_API_DOC_EXCLUDE 参数如何使用？

### ISSUE THREAD

**Issue by happyflyer** [kwkwc/flask-docs#10]
我构建的应用中，同一个蓝图下的endpoints，有的需要生成api文档，有的不需要生成文档，请问如何使用RESTFUL_API_DOC_EXCLUDE 参数设置呢？

**Comment by kwkwc** [comment]
@happyflyer 插件暂时只支持同时开放或隐藏同一蓝图下的 endpoints，**RESTFUL_API_DOC_EXCLUDE** 参数是给 RestfulApi 形式的 endpoints 使用的，例如这个[示例](https://github.com/kwkwc/flask-docs/blob/master/examples/sample/sample_app_restful.py)中的类名为 **TodoList**，如果希望不显示，可以填写类名的小写过滤掉 **app.config['RESTFUL_API_DOC_EXCLUDE'] = ['todolist']**

**Comment by happyflyer** [comment]
非常感谢您的插件，非常好用！！
也非常感谢您的解答！
