### ISSUE TITLE
axios.get使用绝对路径, 导致无法获取子域data

### ISSUE THREAD

**Issue by ziserendexin** [kwkwc/flask-docs#11]
实际使用中,使用了子域路由:
```
192.168.1.1:80/myapp
```
应该获取的地址为:
```
192.168.1.1:80/myapp/docs/api/data
```
但因为这里的使用了绝对路径的问题,导致获取到的地址为
https://github.com/kwkwc/flask-docs/blob/fae5fe8fd9c3595b0d52107fadca3dfc242e2832/flask_docs/templates/index.html#L77
```
192.168.1.1:80/docs/api/data
```
参考下面的处理方式:
https://github.com/axios/axios/issues/882

这里使用相对路径.

比如改为:
```
axios.get('data').then
```
应该就没问题了.

复现方式:

比如使用waitress-serve启动一个带`url_prefix`子域的服务:

```
waitress-serve --port=80 --url-prefix='api' --call 'myapp'
```

**Comment by kwkwc** [comment]
@ziserendexin 谢谢你的反馈，新版本已修改

更改 _**axios.get('data')**_ 为相对路径的方式确实可以获取到包含子域路由的地址
