### ISSUE TITLE
 Flask-Docs error - list index out of range

### ISSUE THREAD

**Issue by 99Kies** [kwkwc/flask-docs#14]
![image](https://user-images.githubusercontent.com/45918704/122649122-fdcaf600-d15e-11eb-88d0-b61bc232ee84.png)
The page was accessible, but the error message left me at a loss.
![image](https://user-images.githubusercontent.com/45918704/122649167-2fdc5800-d15f-11eb-99eb-f5071d3815d4.png)

**Comment by kwkwc** [comment]
@99Kies Thanks for your feedback, new version v0.4.7 has been fixed.

**Comment by kwkwc** [comment]
I just found out that as of June 15th, 2021, the building on travis-ci.org is ceased, so the new version has not been built yet, I'll try to migrate to another build platform later.

**Comment by 99Kies** [comment]
> I just found out that as of June 15th, 2021, the building on travis-ci.org is ceased, so the new version has not been built yet, I'll try to migrate to another build platform later.

look forward to

**Comment by kwkwc** [comment]
@99Kies The v0.4.7 version has been updated manually and can be installed from pip

**Comment by 99Kies** [comment]
I have found the problem, the source in mainland China is still stuck at 0.4.6, I have now used the default source download in PyPI to solve the problem. tks! @kwkwc

**Comment by 99Kies** [comment]
I have a few questions, will this post support swagger?@kwkwc

**Comment by kwkwc** [comment]
Sorry, this plugin does not support swagger.

**Comment by kwkwc** [comment]
I wrote this plugin because I didn't want to use the syntax of a tool like swagger and wanted something a little more free and simple.

**Comment by 99Kies** [comment]
> I wrote this plugin because I didn't want to use the syntax of a tool like swagger and wanted something a little more free and simple.

i like markdown too!

**Comment by 99Kies** [comment]
@kwkwc  I have another question. I want to ask how to add the API document of ErrorHandler in Flask.

**Comment by 99Kies** [comment]
Because this is a unified error reporting API, but maybe some APIs will do custom error handling, will these be implemented.

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/122681529-4817aa00-d227-11eb-9dc5-1f4394b00076.png)
Do you understand what I mean? 😂

**Comment by kwkwc** [comment]
Do you mean that different APIs use the same documentation description? 😂

**Comment by 99Kies** [comment]
> Do you mean that different APIs use the same documentation description? 😂

Yes, Of crouce a few APIs might say differently.(It can be understood that it is editable)

**Comment by kwkwc** [comment]
可以看这里 #13，加了个装饰器 @ApiDoc.change_doc

**Comment by 99Kies** [comment]
原来是国人  这有道翻译累死了，蟹蟹啦，我正在往我的架构里引入flask-docs。确实十分方便。

**Comment by kwkwc** [comment]
能帮助到你就好，README 最下面那里有示例😂

**Comment by 99Kies** [comment]
嗯 是的，就是和他一样的问题，这块会添加到下一个版本吗

**Comment by kwkwc** [comment]
这个装饰器已经有了，可以直接使用的

**Comment by 99Kies** [comment]
@ApiDoc.change_doc   ok 懂了

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/122684555-98e3ce80-d238-11eb-8335-4311eebc843b.png)
为什么每个路由下都有一个相同的接口，这个是为什么？

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/122684640-1dcee800-d239-11eb-86ef-f5bec54d7764.png)

**Comment by kwkwc** [comment]
这个接口是写在哪里的呢，方便贴下定义部分的代码吗

**Comment by 99Kies** [comment]
@kwkwc  哪个接口？是apidoc的定义声明吗？

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/122919685-1a4f7400-d393-11eb-9174-41f5f5df2dac.png)
我这里admin路由下并没有声明api，也有一个默认的send接口。

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/122919886-5682d480-d393-11eb-8436-5c11e73ed3cf.png)
是因为这个static_folder参数，这个算flask-docs的bug了吧

**Comment by kwkwc** [comment]
并不是 BUG，因为在使用 static_folder 的时候 Flask 会自动注册路由，相当于这是一个 GET 方法的 API，可以用于直接获取文件，你在每个 Blueprint 都使用了 static_folder 参数，所以在 Flask-Docs 界面也会全部显示出来。

**Comment by kwkwc** [comment]
我先关闭这个 issue 了，如果有其他问题再开新的吧

**Comment by 99Kies** [comment]
> 并不是 BUG，因为在使用 static_folder 的时候 Flask 会自动注册路由，相当于这是一个 GET 方法的 API，可以用于直接获取文件，你在每个 Blueprint 都使用了 static_folder 参数，所以在 Flask-Docs 界面也会全部显示出来。

flask-docs 可以设置取消吗

**Comment by kwkwc** [comment]
暂时没有这么细的展示权限控制，但是就算支持，像你这种情况也是比较难处理的，因为用 static_folder 的时候，路由是 Flask 自动注册的，static_folder 名称是用户自定义的，有可能出现 a/static、b/static、a/static_test、b/test 等名称，这个是很难过滤的，有点我不是很明白，你为什么需要在每个蓝图都注册 static_folder，然后暴露相同的 static_folder，如果只是为了暴露 static_folder，但又不想在 Flask-Docs 界面显示，你可以专门添加一个新的蓝图，然后不在 API_DOC_MEMBER 配置里面填写就行
