### ISSUE TITLE
如何让/docs/api显示在api文档下的路径

### ISSUE THREAD

**Issue by 99Kies** [kwkwc/flask-docs#15]
我在和前端同学沟通的时候出现了一些问题，因为 <http://xxxxxxxxx/docs/api/>  下的操作不会改变url的路径，所以每次我和他沟通的时候都只能截图给他看
![image](https://user-images.githubusercontent.com/45918704/123788341-7758a600-d90e-11eb-86de-0db52bb4eebc.png)

就像这样子

**Comment by kwkwc** [comment]
我感觉每次截图和发一条带锚点的链接成本其实差不了多少......不过考虑到便利性，后续可以尝试添加

其实你也可以只发接口名称让他搜索

**Comment by 99Kies** [comment]
> 我感觉每次截图和发一条带锚点的链接成本其实差不了多少......不过考虑到便利性，后续可以尝试添加
> 
> 其实你也可以只发接口名称让他搜索
