### ISSUE TITLE
请求体非json格式报错

### ISSUE THREAD

**Issue by 0Jvang** [kwkwc/flask-docs#16]
请求体这种格式能正常返回，但同时会弹出Error The request body is incorrect，有误导作用
```
url=www.baidu.com&encrypt_type=aes
```

**Comment by kwkwc** [comment]
你好，请问添加 **headers** 了吗，如果没指定，在非 **GET** 或 **DELETE** 请求下默认会尝试将请求的 **body** 编码为 **json** 格式，所以会报错，使用 **_content-type:application/x-www-form-urlencoded_** 可去除报错提示

**Comment by 0Jvang** [comment]
好的，谢谢
