### ISSUE TITLE
Hi，我是csdn的柠檬

### ISSUE THREAD

**Issue by heannycn** [kwkwc/flask-docs#17]
主要有几点
1. 如果允许的话，我会创建个分支，做一些更新，然后您来确定是否mr；
2. 我觉得本仓库的目的是为了更好的对api做文档注释，至于文档描述，放在任何位置都可以，如果放在文档标题的下面也可以做成可隐藏显示等等，当然，主标题也可以放到左边
3. url.split('/')[0]换成了蓝图的标题这个我还没测试，我觉得这个方案挺不错；（我的方案是支持给url.split('/')[0]提供一个中文自定义标题，这样仅仅更灵活一些）

**Comment by heannycn** [comment]
4. 我更倾向于doc.init_app(app)，所以我觉得init_app入参只需要一个app即可，因为当前的版本ApiDoc()里面的title等信息是不可用的，当使用doc.init_app(app)时

**Comment by kwkwc** [comment]
其实在 CSDN 我还没回复完，因为那边私信提示 ”对方尚未回复你，你只能发送3条消息“，我统一在这里回复吧



1、可能你没留意到我这边原始版本是同时支持 **普通的 API** 和 **RESTful API** 的显示，例如下图

![屏幕截图 2021-09-28 224421](https://user-images.githubusercontent.com/12382013/135396802-e95c52d1-2e4d-4964-9dd2-784218db7969.png)

因为在一个项目中可能同时存在不同风格的 API 写法，但应该都需要兼容展示，按你现在的改动之后，**[sample_app_restful.py](https://github.com/kwkwc/flask-docs/blob/master/examples/sample/sample_app_restful.py)** 的示例貌似已经不能运行



2、横向分类标题的问题在我最开始设计时也是考虑过的，但后来放弃了，原因是：在蓝图或 RESTful API 的类名过多的情况下就会出现堆积的问题，类似浏览器的标签栏，例如下图

![屏幕截图 2021-09-30 115449](https://user-images.githubusercontent.com/12382013/135396859-ef14f60a-d7b7-4520-b10a-4d6868bfa02c.png)

所以这也是为什么新版 Edge 等浏览器都开始支持垂直标签栏的原因

设计时我最终的解决方案就是 **垂直展示** + **搜索框**，其实也考虑过添加分类，当时考虑了两种方案

一、就是和你现在的做法一样，添加一个配置项，如果是普通 API 就很好弄，一般蓝图不会很多，手动填写下就可以，但是 RESTful API 就不行了，每个类一个分类，每个都手动写上不太现实；

二、用命名空间或装饰器，这里会遇到三个问题

- 现在支持的 Flask-RESTful 是不支持命名空间的

- 像 Flask-RESTX 支持命名空间，但是代码大部分要重写，因为要同时兼容，我有考虑后续支持 Flask-RESTX

- 用装饰器对用户项目的代码侵入性太高，原来写这项目的原因就是我不想使用像 Swagger 这类文档生成，因为你必须按它要求的格式编写文档，我想要更自由更简单的工具，当然自由是有代价的，太自由就不能做到自动填写请求参数，对比请求响应这类功能了



3、文档描述其实和上面有点类似，上面是横向有问题，这里则是垂直有问题，“放在任何位置都可以” 这个我不太同意，因为会影响整个界面的布局，例如下图

![屏幕截图 2021-09-28 214450](https://user-images.githubusercontent.com/12382013/135396945-ea761fa0-fef0-4710-9554-2a943ae216ef.png)

像你说的确实可以做隐藏，但是隐藏的界限很难界定，例如：描述长度超过多少字符之后隐藏才合适；浏览器的大小缩放到多大才应该决定隐藏或展示；这些都很难界定，所以最终我的方案就是只放在右边，当然可以考虑分开，一个短标题配置，一个长标题配置，但这样感觉太麻烦了，必要性不是很大



4、展示根目录 html 我觉得不应该是 Flask-Docs 的独立功能，正确的做法应该是后端有一个 GET html 的接口



5、”init_app 只有 app 参数“，其实这个对原代码来说并不是修复，而是破坏，init_app 函数一般用在延迟生成实例对象，例如以下代码

```python
apidoc = ApiDoc()

def create_app(config_name):

    app = Flask(__name__, static_folder="static")
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # Flask-Docs
    apidoc.init_app(
        app, title=app.config["PROJECT_NAME"], version=app.config["PROJECT_VERSION"]
    )

```

参数在实际创建时从配置文件中获取，相似的写法可以从 **[Flask-Migrate](https://github.com/miguelgrinberg/Flask-Migrate/blob/main/src/flask_migrate/__init__.py)** 这类三方库找到

```python
class Migrate(object):
    def __init__(self, app=None, db=None, directory='migrations', **kwargs):
        self.configure_callbacks = []
        self.db = db
        self.directory = str(directory)
        self.alembic_ctx_kwargs = kwargs
        if app is not None and db is not None:
            self.init_app(app, db, directory)

    def init_app(self, app, db=None, directory=None, **kwargs):
        self.db = db or self.db
        self.directory = str(directory or self.directory)
        self.alembic_ctx_kwargs.update(kwargs)
        if not hasattr(app, 'extensions'):
            app.extensions = {}
        app.extensions['migrate'] = _MigrateConfig(
            self, self.db, **self.alembic_ctx_kwargs)
```



6、"doc 文档标题非第一行也可以捕捉到"，这个对原代码来说其实也是破坏，假设有一个 API 的注释写法如下

```python
@api.route("/delete_data", methods=["GET"])
def delete_data():
    """
    
    {"code": xxxx, "msg": "xxx", "data": null}
    """

    return jsonify({"api": "delete data"})
```

那么你生成文档的界面将会是这样的

![屏幕截图 2021-09-28 230924](https://user-images.githubusercontent.com/12382013/135396990-d182c1c3-a032-4125-ad42-15112d64b081.png)

首先要明确一点，函数的注释是用户填写的，用户什么都有可能写上

你的改动相当于要求用户必须写上函数的标题，但是问题在于你没办法强制用户的做法，所以强行取第一次出现的字符串就会出现上图的问题，当时设计时我最终的方案就是：只取第一行的文字，如果不存在，就不展示副标题，类似的方案也可以在 Flask-RESTX 自动生成的 Swagger 文档体现出来



7、在你的 **[文章](https://www.heanny.cn/post-506.html)** 中提到的一些说明和修复我有些不太明白，因为只有文字描述比较抽象



8、另外你的前端代码修改成了 \<style\>\</style\>\<template\>\</template\>\<script\>\</script\> 的顺序，建议可以浏览下  **[风格指南 — Vue.js](https://cn.vuejs.org/v2/style-guide/#%E5%8D%95%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6%E7%9A%84%E9%A1%B6%E7%BA%A7%E5%85%83%E7%B4%A0%E7%9A%84%E9%A1%BA%E5%BA%8F%E6%8E%A8%E8%8D%90)**



9、顺便报个 BUG，在我用的 Firefox (v92.0.1) 下文档界面右上角的调试按钮和下载按钮无法点击



10、谢谢对项目的关注，欢迎提交代码；功能方面的提交希望保持自由、简单，没有过大的侵入性，但界面方面的提交希望没有过大的改动，因为用户有可能是个人，也有可能是企业等，所以界面应尽量保持统一、简洁

**Comment by heannycn** [comment]
领教了，非常感谢
因为最近在做的一个小项目用了蓝图红图，就对该项目做了一些魔改，更适用那个项目，所以考虑不周，望见谅
文章只是按照我的使用习惯做了魔改后写的，请忽略，

**Comment by kwkwc** [comment]
因为你的很多修改刚好也是我之前踩过的坑，所以写得比较详细，也算是做个记录吧，以后其他人遇到也可以作为参考

**Comment by heannycn** [comment]
哦对了，第九点，那个bug是因为副标题相关问题引起的(按钮使用了float: right;)，其他浏览器也有，我可能参考本项目重新写一个，届时还望指正。
顺便，使用bp_name = rule.endpoint.split(".")[0]的方式带来了很多好处，这点我很喜欢，他应该固定是length=2的，所以我调整的按照三段区分的就会失效

**Comment by kwkwc** [comment]
指正谈不上，大家一起交流

我现在在想为什么之前没用 rule.endpoint，是不是有什么坑点忘记了
