### ISSUE TITLE
The route args are not visible in the url

### ISSUE THREAD

**Issue by ptutak** [kwkwc/flask-docs#18]
If in the route there are args in the form:
`/my_route/<arg1>/something/<arg2>`

They are not visible in the "url". The generated "url" is in the form:
`/my_route//something/`

Which is due to the fact, that markdown is getting rid of <arg1> statements.

Suggested change:
In the index.html replace the 327 ilne

https://github.com/kwkwc/flask-docs/blob/0ecadc0352a44d691917b6dd49ffb83833cbe769/flask_docs/templates/index.html#L327

with:
```
md += "- `" + urls[i].replace(/\t/g, " ") + "`\n\n"
```

**Comment by kwkwc** [comment]
Thank you for your feedback, you can update the version or add type before arg to solve this problem, for example:

`/my_route/<int:arg1>/something/<string:arg2>`
