### ISSUE TITLE
能否直接生成离线文档？

### ISSUE THREAD

**Issue by MengDanzz** [kwkwc/flask-docs#19]
需求：在CI/CD流水线中生成文档并放到内网服务器方便查阅，但并不希望公开到外部。
对于文档可见性问题，找到了是否公开的配置项，可以在生产环境和开发环境分别设置。
但是其他模块想要调用该模块的接口，他们clone这个项目的代码并运行就太麻烦来，因此希望能直接生成离线文档

**Comment by kwkwc** [comment]
你好，运行起来后可以在界面下载离线文档

**Comment by MengDanzz** [comment]
我觉得可以把这个功能做成一个flask 命令，例如运行：
`flask docs`
 生成离线的html或者markdown，而不需要运行应用程序本身

**Comment by kwkwc** [comment]
暂时没有这功能，不过确实可以考虑加上

**Comment by MengDanzz** [comment]
我在我的项目中实现了这个功能，顺便把这个功能迁移到了flask_docs代码，并提交了PR，请您审核下 #20
