### ISSUE TITLE
简化书写注释的一个建议

### ISSUE THREAD

**Issue by TotoroQwQ** [kwkwc/flask-docs#47]
一直在用大佬你的这个插件，以前在你这个插件上重写方法，然后实现了些好玩的功能。后面想推给同事也用，删减了大部分。
现在是舍去了绝大部分自定义功能，极大简化注释书写。因为很多时候大家并不想为了一二十行代码写几十行注释，看代码时也麻烦。文档也相当于是自己写的，而不是“自动”生成的。
我现在的逻辑是:
1. 固定了一个接口页面模板，对于使用者就是内置模板，这个模板定制性非常强，但是一般来说用作与别人对接是比较够用且通用的：
```python

content = """
    @@@
    ### 接口描述
    {0}

    ### 可传参数
    | 参数名 | 参数说明 |
    |--|--|
    {1}

    ### 返回字段
    | 字段 | 说明 |
    |--|--|
    {2}

    ### 返回样例
    *仅表现数据结构样式*
    ```json
    {3}
    ```

    {4}
    @@@
"""
```
2. 接口代码注释规范化如下，因为是标准的注释，解析起来也就比较方便，我可以自动获取【接口描述】【请求参数及说明】【返回样例】并填充到上面的模板中。注释缺少哪一项，对应文档这一块就是空的，后面补上也好补。

另外，考虑到实际其实很多人不喜欢写【:return：】的详情，在APIDOC(ret=None)增加了ret参数，可以是一个类也可以是一个对象，我会获取这个类__init__方法的参数注释，然后分析出返回字段，并生成对象，获取一个返回样例。
```python
APIDOC()  # 自动生成在线文档  重写的一个注解
@route(xxx)
def test():
···
    这是一个测试接口描述
    :param v1: 这是第一个参数
    :param v2: 这是第二个参数
    :return: 这是返回数据
···
    return None
```

这样，我基本只用正常写注释，就可以自动生成接口文档。使用起来非常方便。
当然，这是高度自定义后的结果，失去了大量的自定义空间。但有时这种使用会更加广泛，简单方便快捷才是最好的。
可以适当内置这种类似的简易模式，需要自定义的话，可以自己改模板以及对注释解析的方法就行，或者像现在这样不使用模板。
附几张图
![image](https://github.com/kwkwc/flask-docs/assets/8982154/ba1a1ca8-5c9d-4471-8453-5cf923d6c271)
![image](https://github.com/kwkwc/flask-docs/assets/8982154/52e00444-b0d1-46e6-a9eb-5dd871e461f5)

![image](https://github.com/kwkwc/flask-docs/assets/8982154/85b4abaf-4365-4d3d-ae90-2683c8bb84df)

**Comment by kwkwc** [comment]
感谢你对项目的关注和建议，以下是我对你的建议的部分解答和看法：

1.如果只是想减少重复注释，可以使用 `@ApiDoc.change_doc` 装饰器

2.先看下面的函数：

```python
def my_func():
    """
    我是注释 我是注释 我是注释
    """
```

`我是注释 我是注释 我是注释` 部分在 Python 里是注释，意味着用户可以在这里以 `任何格式` 写 `任何文字`，像你的项目代码，注释用的是 `reStructuredText` 风格，并不是标准的注释：

```python
def function_name(param1, param2):
    """Function summary line.

    :param param1: The first parameter.
    :type param1: int
    :param param2: The second parameter.
    :type param2: str

    :return: The return value. True for success, False otherwise.
    :rtype: bool
    """
```

Python 还有其他几种风格的注释，例如 `Google` 的，像这样：

```python
def function_name(param1, param2):
    """Function summary line.

    Args:
        param1 (int): The first parameter.
        param2 (str): The second parameter.

    Returns:
        bool: The return value. True for success, False otherwise.
    """
```

用户还可以按他自己的风格写：

```python
def function_name(param1, param2):
    """Function summary line.

    my_args:
    arg1: The first parameter.
    arg2: The second parameter.

    my_returns: The return value. True for success, False otherwise.
    """
```

所以 `Flask-Docs` 一开始的设计就是无论用户怎么写，只要用 `@@@` 包裹就解析成 `Markdown` 展示，不包裹的就原封不动展示，这样相当于有了统一的标准，不然面对一段未知格式的文字根本无从处理（最新版本会直接默认全部解析成 `Markdown`，不需要 `@@@` 包裹，因为要兼容其他插件的 `Swagger` 文档，避免出现 `@@@` 符号）

其实当你定义好了你的内置模板，写好了默认的注释处理方法，更难的是要 **说服** 你的用户、你的协作者们按你的标准去书写注释，注释里面多一个符号少一个符合都是一个坑

3.`接口参数` 用 `函数参数` 的注释风格来定义其实表达能力不够，例如在你的例子里面，`返回字段` 只有 `字段` 和 `说明`，这样相对比较容易处理，但是 `可传参数` 就不一样了，大部分情况下会像下面这样：

|  args | required | location |  type  |  help    |
|-------|----------|----------|--------|----------|
|  name |  true    | query    | string | todo name |
|  type |  false   | body     | string | todo type |

同样的，你不知道用户会怎样书写注释，这时候你可能需要定义自己的一套规则，例如这样：

```python
def function_name(param1, param2):
    """Function summary line.

    :param: name
        required: true
        request_type: query
        type: str
        remarks: todo name
    :param: type
        required: false
        request_type: json
        type: str
        remarks: todo type
    """
```

这样相当于需要实现 `你的规则` 转换成 `Markdown` 的方法，同样的，你需要让用户按你的规则书写参数，所以直接写 `Markdown` 是不是会更简单一些......

4.`Flask` 的项目很多都会使用 `Flask-RESTful`、`Flask-RESTX` 这类插件，像 `Flask-RESTX` 定义完参数后其实已经不需要上面第 3 点的手写参数说明了，本身已经自带 `Swagger` 的接口文档，会自动生成，`Flask-Docs` 的配置项 `API_DOC_AUTO_GENERATING_ARGS_MD` 设置为 `True`，可以提取一部分数据，不过暂时只是实验性质，可以运行代码库的示例查看，平时我自己的项目也会用到 `Flask-RESTX`，但是会用 `Flask-Docs` 自动生成接口参数，然后手写 `Markdown` 作为其他信息的补充，还有用 `Flask-Docs` 的调试功能，当然这些看个人喜好

以上就是我个人的看法，欢迎一起讨论

**Comment by TotoroQwQ** [comment]
#### 1. 需求来源

我最开始的想法就是从`@ApiDoc.change_doc`开始的。
一开始想法是文档尽量写详细，人人拿着就能看懂。但在一些中小型接口对接工作中(顶天2/30来个接口对接)，一是大部分精力还是在开发上，程序跑通了测完了再去写详细的文档还是会费些时间。然后最关键的是，有时候涉及多人任务，或者项目移交。**别人是不会写文档的**。每次教同事，也是成本。
后来思路就是，如何便捷，无感的形成文档。所以引入了内置模板。而我的工作只负责让同事按reStructuredText 风格写注释，这就简单多了。
(标准注释这个，我理解的就是广泛使用，有固定规则的，python应该是没有官方定义的注释格式)
内置模板还有一个好处，就是**风格统一**，不然多人写的文档，或者一个人忙时/闲时写的文档风格都会有不同，会乱糟糟的。

#### 2. 说服用户

当然，作为一个插件/工具，或者说是产品。过于定制化，用户接受度就一定小。
换个思路，与其去说服用户，不如让用户选择。适当**增加**内置模板和指定的“通用形式的注释”**的选择**，让用户自己选择用不用。
而一个模板和注解解析的方法，也不过几十行代码。即使用户有自己的注释风格，重写解析方法也不难，作为给一个大项目或者多个小项目通用框架中的方法，这个**成本完全不算高**。
当然，混乱的注释风格可能带来奇怪的页面效果，这个可以简单的在使用时给出说明，或者兼容reStructuredText /google两种注释风格，好像就这两种用得最多一些。
如果用户觉得麻烦，也完全可以不选择这种内置模板方式，并没有什么损失。

#### 3. 传入参数

这个问题不大。如果一个用户选择了这种简易的内置模板模式，他是会妥协一些详情的。我现在是支持2-3行，【字段名称】【字段类型】【说明】，有什么多余的信息，都放在说明里面就好，一般会在说明中多记录个`是否必传`。
```
:param v1: <int> 这是一个参数
:param v2: 这是第二个参数
```
简易模式这样就行了，必要信息都有了。大部分情况下，这些就够用了，无论对外对接还是内部交流。

提供一个简易模式，用户来选择用不用。**不是让用户接受这种注释类型，而是如果他能接受，他可以选择这种模式省很多事。**
而且像第二点说的，如果用户有自己的注释风格，无论他是一个大项目，还是像我这样整合了一个小的接口框架，在多个小项目中不断复用，自己按照自己风格来重写这个解析方法。也比一直写大量的md格式文档舒服得多。

**毕竟程序员都不太喜欢写文档，而写注释是一个好习惯。**

#### 4. Flask-RESTX

因为我这边是自己整合的一个尽可能简单接口对接框架，还没有使用这个，后面我学习下再看看。


这些都只是个人经历和见解，自己感觉好用和够用，没有统计过这方面的需求  XD

**Comment by kwkwc** [comment]
我不赞成的原因是：从前面的示例来看，参数还是手写的，和原来并没有太大区别，而且需要维护一套自定义的的书写规则和解析器

下面举例：

```python
# 这里定义一些公用数据

# 注释模板
content = """
    ### 入口参数
    | 参数 | 说明 |
    |--|--|
    {req}
"""

# 入口参数
# param1 第一个参数
# param2 第二个参数
```

1.用你的方式

```python
class APIDOC():
    def my_rule_to_md(self, str):
        ......
        return md

class QueryCmd_Req_Entity():
    def __int__(self, **args):
        """
        :param param1: 第一个参数
        :param param2: 第二个参数
        """

@APIDOC(req=QueryCmd_Req_Entity)
def api():
    """
    """
```

2.用你的书写方式 + `@ApiDoc.change_doc`

```python
def my_rule_to_md(str):
    ......
    return md

class QueryCmd_Req_Entity():
    req = """
    :param param1: 第一个参数
    :param param2: 第二个参数
    """

@ApiDoc.change_doc(
    {
        "docs": content.format(
            req=my_rule_to_md(QueryCmd_Req_Entity.req)
        )
    }
)
def api():
    """
    docs
    """
```

3.`Markdown` + `@ApiDoc.change_doc`

```python
class QueryCmd_Req_Entity():
    req = """
    | param1 | 第一个参数 |
    | param2 | 第二个参数 |
    """

@ApiDoc.change_doc(
    {
        "docs": content.format(
            req=QueryCmd_Req_Entity.req.strip('\n').strip()
        )
    }
)
def api():
    """
    docs
    """
```

假设模板需要修改成这样：

```python
content = """
    ### 入口参数
    | 参数 | 说明 | 是否必须 | 是否加密 | 类型 | 默认值 | 可选项 | xxx |
    |--|--|--|--|--|--|--|--|
    {req}
"""
```

第 1 种方式可能这样改：

```python
class QueryCmd_Req_Entity():
    def __int__(self, **args):
        """
        :param param1: 第一个参数 | 是 | 是 | string  | a    | a/b/c/d    | xxx
        :param param2: 第二个参数 | 否 | 是 | boolean | true | true/false | xxx
        """
"""
```

第 3 种方式这样改：

```python
class QueryCmd_Req_Entity():
    resp = """
    | param1 | 第一个参数 | 是 | 是 | string  | a      | a/b/c/d    | xxx |
    | param2 | 第二个参数 | 否 | 是 | boolean | true   | true/false | xxx |
    """
"""
```

所以具体的区别和简化暂时没体现出来

**Comment by kwkwc** [comment]
`换个思路，与其去说服用户，不如让用户选择` 这个我也是赞同的，其实你的思路是很好的，`Flask-RESTX` 就是类似你这样的设计，装饰器传递了入口参数和出口参数，只不过不需要手写注释而是用代码定义，然后扩展实现了参数检验，参数拦截等功能，有空可以看看参考下，当初写 `Flask-Docs` 就是想自由点不想被规则绑死，这里可以看到我之前设计时候的一些思考，也是对另外一个用户的回答 #17，希望对你也有帮助

**Comment by TotoroQwQ** [comment]
`当初写 Flask-Docs 就是想自由点不想被规则绑死`
哈哈，思路确实有不同。我这边整合的简易框架是尽量让研发注重各个项目中逻辑部分代码，框架包含了基本的flask，log，flask_docs等等，但给同事用的时候甚至不用知道这些，会基本python，会写逻辑方法就行。方法上面加`@route（xxx)`就变接口，加`@APIDOC（）`就自动生成文档。

`所以具体的区别和简化暂时没体现出来`关于这个
1. 你的例子中确实工作量差不多。并且可拓展性大大降低了。但是工作性质是不一样的。写resp属性是额外工作量，写参数注释是本职工作。一般来说，即使写了resp属性，也得再写一遍参数注释，，不然代码阅读性会变差，尤其是枚举值参数。

    比如我同事开发了几个接口，转眼来问，文档怎么都是空的，我可以直接说一句，你把参数注释写完整。如果是第三种方案，我说你在接口方法下面写个传入参数的md文本，返回类里面你写个resp属性，里面写返回字段的md文本。会被追问怎么写，哪些类要写哪些不用写。沟通成本增加，他需要理解整个文档形成的原理。

2. 可阅读性，md好用，但直接写在代码注释里面，也挺不好看的。不用模板吧，大量重复，20行代码50行md文本，用模板吧，经常得去看看模板找找上下文。参数注释就好得多。

3. 工作量有少量降低。解释器不仅是解析出resp的字段内容，我这个接口里面不需要传参所以没写，它同样会解析传入参数，以及生成【返回样例的json串】。一般接口会是下面这样，整个文档就写完了。文档页面只要是哪里没有数据，就是哪里注释没写。也不用等接口通了再复制一个返回样例补到文档里面。

4. 可拓展性，这个确实是硬伤。不过选择简便，这就是代价。不拓展是最好的哈哈
```
class APIDOC():
    def my_rule_to_md(self, str):
        ......
        return md

class QueryCmd_Resp_Entity():
    def __int__(self, **args):
        """
        :param return1: 第一个字段
        :param return2:<int> 第二个字段
        """

@APIDOC(ret=QueryCmd_Resp_Entity)
def api():
    """
    这是接口描述
    :param param1: 传入参数1
    :param param2: <int> 传入参数2
    """
```

Flask-RESTX看起来不错，得空了试一试

**Comment by kwkwc** [comment]
不好意思，写得急，上面示例把入参和出参混在一起写了，主要想表达的是入参，现在已经修正

1.在我看来，函数参数注释和接口参数注释还是不太一样的，像函数本身就可以体现一些参数的默认值、是否必须、类型等信息，所以函数参数注释可以写少点，接口参数就不一定，很多时候外部调用者最直观了解接口的方式就只有 API 文档，我觉得应该要详细，当然像上面那样，就字段和说明两项，把额外的都写到说明里面，也没什么问题，愿意写我觉得就已经很好了，毕竟大部分人根本不写文档

2.这个真的说到痛点了，以前写 `Flask-Docs` 的原因就是代码文档分离（经常忘记更新文档），还有不想对代码有太大入侵性（安装引入就可以直接展示文档，不用改接口代码），后来用了 `Flask-Docs` 情况稍微好点，毕竟代码和文档在一起，然后又遇到第 2 点这个问题，不过我更倾向于不用模板的方式，我自己的项目一般会把文档都写到接口注释里，接口函数只作为入口，一般都在文档最下面才跳到真正的处理函数，这样分开代码和注释

下面是比较完整的示例，应该能满足大部分需求吧（除了不想写 md）：

```python
content = """
    ### 入口参数
    {req}

    ### 返回字段
    | 字段 | 说明 |
    |--|--|
    {resp}

    ### 返回示例
    ```json
    {return_json}
    ```
"""

class QueryCmd_Req_Entity():
    req = """
    | 参数 | 说明 | 是否必须 | 是否加密 | 类型 | 默认值 | 可选项 | xxx |
    |--|--|--|--|--|--|--|--|
    | param1 | 第一个参数 | 是 | 是 | string  | a      | a / b / c / d    | xxx |
    | param2 | 第二个参数 | 否 | 是 | boolean | true   | true / false | xxx |
    """

class QueryCmd_Resp_Entity():
    resp = """
    | return1 | 第一个字段 |
    | return2 | 第二个字段 |
    """

@ApiDoc.change_doc(
    {
        "这是接口描述": xxxxx,
        "content": content.format(
            req=QueryCmd_Req_Entity.req,
            resp=QueryCmd_Resp_Entity.resp.strip('\n').strip(),
            return_json=json
        )
    }
)
def api():
    """这是接口名称

    这是接口描述

    content
    """
```
