### ISSUE TITLE
Fork and rework

### ISSUE THREAD

**Issue by Seluj78** [kwkwc/flask-docs#7]
Hi !

First of all, thanks for `flask-docs` ! It was exactly what I was looking for and I used it on `https://api.exploreve.fr/docs`

But I modified it (see https://gitlab.com/exploreve/backend/-/blob/develop/tropobackend/utils/docs.py and https://gitlab.com/exploreve/backend/-/tree/develop/tropobackend/templates/apidoc)

I need some more flexibility in the titles and the way things were displayed.

I am thinking of forking your project and either releasing it as a standalone or making a big merge request. Which one would you prefer ?

I hope you and your family is safe
Best
Jules

**Comment by kwkwc** [comment]
@Seluj78 

Hi Jules !

Thank you for your support ! I suggest you release it as a standalone, which will be more convenient for you to modify, because I seldom update this project now. 

I hope you and your family is safe, too
Best

**Comment by Seluj78** [comment]
Thanks for the reply ! I'll let you know when I get something working !

Have a great day 🙌
