### ISSUE TITLE
flask-restful下会出现重复方法

### ISSUE THREAD

**Issue by thep0y** [kwkwc/flask-docs#8]
![20200515092816](https://user-images.githubusercontent.com/51874567/82001735-7626d400-968e-11ea-9104-e4e378be1922.jpg)

一个Resource下出现两个GET方法，请问怎么处理？

**Comment by kwkwc** [comment]
@thep0y 
已更新，新版本 v0.1.4 合并了相同路由的 URL 和 Method，应该不会重复显示了
